# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build my Zen'
on: push
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corneish_zen_v2_left","corneish_zen_v2_right"]'
      branches: '["zmkfirmware/zmk/main caksoylar/zmk/caksoylar/zen-v1+v2+experimental"]'
